samples:
    d2337: /storage/macchiato/complgen3/results/nbd/promethion/hg19s/exp20180216_d2337_wouter/fastq
    d8250: /storage/macchiato/complgen3/results/nbd/promethion/hg19s/exp20180223_d8250_wouter/fastq
    d6843: /storage/macchiato/complgen3/results/nbd/promethion/hg19s/exp20180207_wouter_d6843_2/fastq
    d7463: /storage/macchiato/complgen3/results/nbd/promethion/hg19s/exp20180216_d7463_arne/fastq
    d20615: /storage/macchiato/complgen3/results/nbd/promethion/hg19s/exp20180223_d20615_arne/fastq
