samples:
    sampleA: /path/to/sampleC/fastq
    sampleB: /path/to/sampleC/fastq
    sampleC: /path/to/sampleC/fastq

genome:
    /path/to/database/genome.fa.gz

annotbed:
    /path/to/database/annotation.bed.gz

vcfanno_conf:
    /path/to/configuration/vcfanno_conf.toml

parameters:
    survivor_distance: 500
    survivor_high_confidence_distance: 500
    survivor_high_sensitivity_distance: 100
