samples:
    sampleA: /path/to/sampleA/fastq
    sampleB: /path/to/sampleB/fastq
    sampleC: /path/to/sampleC/fastq

genome:
    /path/to/database/genome.fa.gz

parameters:
    survivor_distance: 500
